version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # --- NEW: Change into the lambda directory ---
      - cd lambda
      - pip install --target ./package -r requirements.txt
  build:
    commands:
      # The build process is now inside the 'lambda' directory,
      # so it can find the lambda_function.py file.
      - cp lambda_function.py ./package/
      - cd package
      - zip -r ../deployment_package.zip .
artifacts:
  # Tell CodeBuild where to find the artifact relative to the project root
  base-directory: 'lambda'
  files:
    - deployment_package.zip